### ISSUE TITLE
Plugin ID mismatch

### ISSUE THREAD

**Issue by Quorafind** [TilBlechschmidt/obsidian-plugin-abcjs#1]
Your plugin could not be installed from obsidian plug-in market. Could you fix the Plugin ID issue?
Thanks!

**Comment by TilBlechschmidt** [comment]
Hey there!
Thanks for notifying me, totally overlooked that identifier 🙈 

It should be fixed in [v1.0.2](https://github.com/TilBlechschmidt/obsidian-plugin-abcjs/releases/tag/1.0.2). Feel free to close this ticket if it works for you now!

**Comment by Quorafind** [comment]
@TilBlechschmidt Thanks again for your work.
