### ISSUE TITLE
Support for passing options to `renderAbc`

### ISSUE THREAD

**Issue by simonjbeaumont** [TilBlechschmidt/obsidian-plugin-abcjs#16]
Would it be possible to add an options page where we can pass some options to the `renderAbc` call?

Specifically, I'm looking to render tabs as described in the docs here:

https://paulrosen.github.io/abcjs/visual/tablature.html#general-structure

which involves calling abc as follows:

```js
abcjs.renderAbc("paper", abc, {
	tablatures: [
		{
			// first violin options
		}, {
			// second violin options
		}, {
			// viola options
		}, {
			// cello options
		}
	]
})
```

**Comment by TilBlechschmidt** [comment]
I can see two options here, where we have an options page which:

1. Allows you to paste a JSON options string that is handed directly to `abcjs`
2. Provides a full interface for the options available in abcjs

However, the settings set by this would apply globally to all code blocks. I suppose that is not necessarily what you want?
Another option I could think of would be to have a special prefix line in the code block where you can add options (similar to YAML frontmatter in a note).

**Comment by simonjbeaumont** [comment]
I'd be happy with any method really. Thanks for you response!

**Comment by simonjbeaumont** [comment]
IIUC this would be necessary for also supporting transposition?

**Comment by asukhodko** [comment]
That would be a great improvement! And I would also be happy to take this feature.

**Comment by goonix** [comment]
This would be most helpful!

**Comment by malcolmgroves** [comment]
Would also love this, for exactly the same reason (tablature support)

**Comment by TilBlechschmidt** [comment]
As this has been a much requested feature, I have taken some time and implemented this. With the new release `1.0.6` you can add a block of JSON to the beginning of your code blocks followed by three dashes `---`. This will be parsed and added to the default options (which can also be overwritten). If the JSON is invalid, a big red banner will be shown to notify the user as just printing it to the developer console is likely not going to be noticed 🙂 

For more details, consult [the new README section](https://github.com/TilBlechschmidt/obsidian-plugin-abcjs#custom-options).

@simonjbeaumont if you could give this a test and see if this suits your original use-case that would be appreciated! You may then close this ticket.

**Comment by malcolmgroves** [comment]
Thanks for the update on this. 

I updated the plugin and using your example from the readme I indeed got the paddingtop happening. 

However when I try and get the tablature to appear using the example at  https://paulrosen.github.io/abcjs/visual/tablature.html I'm having less success. 

My block looks like this:

````
```music-abc
{
  "tablature": [{"instrument": "violin"}]
}
---
X:1
T: Cooley's
M: 4/4
L: 1/8
R: reel
K: G
|:D2|EB{c}BA B2 EB|~B2 AB dBAG|FDAD BDAD|FDAD dAFD|
```
````
However the output is the same as if I left the options off. No errors, but no tablature. 

Probably my mistake but I can't see it.

**Comment by TilBlechschmidt** [comment]
Looks correct to me according to the docs and plugin implementation, I’ll have a detailed look at it tomorrow. Looking at the PR for abcjs and the creation date of this plugin it could be that the bundled abcjs version is simply outdated and does not have the feature yet (see https://github.com/paulrosen/abcjs/pull/737 which is from late 2021). If that’s the case, it should be an easy fix 🙂

**Comment by TilBlechschmidt** [comment]
Yep, that appears to be it. The PR was merged Dec ‘21 and this plugin bundles version 5.12 which was released three years ago. I’ll bump that up to the latest version tomorrow!

**Comment by TilBlechschmidt** [comment]
@malcolmgroves I published version `1.0.7` which now includes the latest version of AbcJS. In my local testing with your example, tablatures seem to work. Could you please verify that they work for you as expected after updating the plugin?

**Comment by malcolmgroves** [comment]
Updated and works perfectly. Thanks for the responsiveness on this.

I still have many questions, but they are abc.js questions, so you're off the hook :-) 

Cheers

**Comment by TilBlechschmidt** [comment]
No problem and happy composing!

Phew, so I can go on vacation without worries now! 🙈
