### ISSUE TITLE
Is it possible to add an option to change the default font color?

### ISSUE THREAD

**Issue by Quorafind** [TilBlechschmidt/obsidian-plugin-abcjs#2]
When I used black theme, the score can’t be read clearly

**Comment by TilBlechschmidt** [comment]
Good point! I was using a white theme and didn't notice. The plugin currently adds a number of classes to the generated output — a list of them [can be found here](https://paulrosen.github.io/abcjs/visual/classes.html#classes).

However, long term it probably makes sense to include some default styles in the [plugins styles.css](https://github.com/TilBlechschmidt/obsidian-plugin-abcjs/blob/master/styles.css) which switch the color to white when dark mode is enabled.

**Comment by TilBlechschmidt** [comment]
For now, you can include the following snippet in your custom theme:
```css
:not(.abcjs-top-of-system)[class*='abcjs'] {
        fill: white;
}
```

**Comment by Quorafind** [comment]
@TilBlechschmidt Thanks!

**Comment by kankaristo** [comment]
You can also use a CSS filter:
```
.theme-dark .abcjs-container {
    filter: invert(1) hue-rotate(180deg);
}
```

`invert(1)` inverts all colors. The `hue-rotate(180deg)` part should keep non-grayscale colors somewhat correct (red isn't inverted to blue/cyan, etc.), while still inverting black to white. But obviously the colors do change somewhat (if you invert an image, it looks a bit funny).

The `fill: white;` method seems to work equally well, and I'm not sure if it's even possible to have color in abcjs. But I thought I'd leave this here, in case someone finds it useful.

**Comment by TilBlechschmidt** [comment]
@kankaristo Thanks for the hint! 🙂
